version: '3.9'

services:
  db:
    image: symdit/postgresql15-bigm
    restart: always
    container_name: postgresql15-bigm
    ports:
      - '5433:5432'
    volumes:
      - ./script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests
      PGDATA: /var/lib/postgresql/data/pgdata
